"""add deleted_at and parent_id to comments

Revision ID: 77b957fc6fc9
Revises: df27ef6f0a29
Create Date: 2026-08-28 15:23:08.257847

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77b957fc6fc9"
down_revision: Union[str, Sequence[str], None] = "df27ef6f0a29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("comments", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_comments_parent_id"), "comments", ["parent_id"], unique=False
    )
    op.create_foreign_key(
        "fk_comments_parent_id",
        "comments",
        "comments",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_comments_parent_id", "comments", type_="foreignkey")
    op.drop_index(op.f("ix_comments_parent_id"), table_name="comments")
    op.drop_column("comments", "parent_id")
    op.drop_column("comments", "deleted_at")
    # ### end Alembic commands ###
